### Get all the authors
GET http://localhost:8080/authors

### Get a single author by ID
@id = 1
GET http://localhost:8080/authors/{{id}}

### Create a new author
POST http://localhost:8080/authors
Content-Type: application/json

{
  "name": "Jan Kowalski"
}