@id = 1
@authorId=1

### Get all the notes
GET http://localhost:8080/notes

### Get the notes by author's ID
GET http://localhost:8080/notes?authorId={{authorId}}

### Get a single note by ID
GET http://localhost:8080/notes/{{id}}

### Create a new note
POST http://localhost:8080/notes
Content-Type: application/json

{
  "title": "Moja notatka",
  "content": "To jest moja notatka.",
  "authorId": 1
}

### Delete a note by ID
DELETE localhost:8080/notes/{{id}}